# Generated by Django 4.2.3 on 2023-07-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.JSONField()),
                ('ingredients', models.JSONField()),
                ('instructions', models.CharField(max_length=1000)),
                ('date_added', models.DateField(auto_now=True)),
                ('img', models.ImageField(upload_to='image/')),
                ('thumbnail', models.ImageField(upload_to='image/')),
                ('option', models.CharField(choices=[('option1', 'Easy'), ('option2', 'Medium'), ('option3', 'Hard')], max_length=10)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe.tag')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
